import re
from typing import Dict

AI_KEYWORDS = [
    "gpt-",
    "chatgpt",
    "ai-generated",
    "generated by ai",
    "openai",
    "llm",
    "artificial intelligence",
]

TEMPLATE_PATTERNS = [
    "responsible for",
    "successfully delivered",
    "collaborated with",
    "tasked with",
    "proactively",
    "detail-oriented",
    "results-driven",
    "motivated self-starter",
    "track record",
]


def detect_ai_and_template(text: str) -> Dict[str, object]:
    lowered = text.lower()
    ai_mention_count = sum(lowered.count(keyword) for keyword in AI_KEYWORDS)
    template_mention_count = sum(lowered.count(pattern) for pattern in TEMPLATE_PATTERNS)

    ai_generated = ai_mention_count >= 1 or template_mention_count >= 6
    template_generated = template_mention_count >= 4

    generic_patterns = [
        r"responsible for",
        r"team player",
        r"excellent communication",
        r"results[- ]driven",
    ]
    generic_count = sum(1 for pattern in generic_patterns if re.search(pattern, lowered))

    return {
        "ai_generated": ai_generated,
        "template_generated": template_generated,
        "ai_keyword_count": ai_mention_count,
        "template_phrase_count": template_mention_count,
        "generic_pattern_count": generic_count,
    }
